### PR TITLE
feat: add JSON control

### LINKED ISSUE #30: Builtin control components
- [x] Text input
- [x] Textarea
- [x] Number input
- [x] Checkbox
- [x] Select
- [x] Button group
- [x] Radio list
- [x] Checkbox list
- [x] Slider
- [ ] Date/hour
- [ ] Color picker
- [x] JSON code editor

### PR DESCRIPTION
**Pull request by hugoattal**
https://github.com/histoire-dev/histoire/issues/30

### Description

I spent a fair amount of time trying different implementations, tell me what you think...

- A "real" code editor is reaaaally too big of a package. Ace editor is 50MB (https://www.npmjs.com/package/ace-builds) and I couldn't find a lite weight cool code editor.
- I tried to build an editor with a div contenteditable, but it was a real hassle. Caret manipulation is super hard (it gets reset at each keystroke since I triggered shiki to update the div). I could have done it, but with a loooot of effort and a ton of lines of code
- I ended up using a "simple" textarea with a code highlight on top of it (with no pointer event). This is super simple but work like a charm. Still, there's no code editor features (like tab or auto-indent)

Anyway, I believe that we really just need color highlight, no-one's going to use Histoire as a real code editor.
Also, I auto indent only on load, but not after (because it can mess up the content during edition if I do it at each update).

Note: The lite/dark mode is not reactive, you must refresh the page. I'm not quite sure how to do that, if you have any idea.

### Additional context

image

image

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

**Comment by Akryum** [comment]
> A "real" code editor is reaaaally too big of a package. Ace editor is 50MB ([npmjs.com/package/ace-builds](https://www.npmjs.com/package/ace-builds)) and I couldn't find a lite weight cool code editor.

You sure? Bundling Ace editor looks to be [less than 400kB(minified)/106kB.gzip](https://bundlejs.com/?q=%28import%29ace-builds%2Fsrc%2Face.js%2C%28import%29ace-builds%2Fsrc%2Fmode-json.js%2C%28import%29ace-builds%2Fsrc%2Ftheme-xcode.js&treeshake=%5B*+as+ace%5D%2C%5B*+as+aceModeJson%5D%2C%5B*+as+theme%5D&text=%22console.log%28ace%2C+aceModeJson%2C+theme%29%22).

For the [Vue Repl](), we use codemirror which is light, weighting around [170kB/57kB.gzip](https://bundlejs.com/?q=%28import%29codemirror%2C%28import%29codemirror%2Fmode%2Fjavascript%2Fjavascript.js%2C%28import%29codemirror%2Fmode%2Fcss%2Fcss.js%2C%28import%29codemirror%2Fmode%2Fhtmlmixed%2Fhtmlmixed.js%2C%28import%29codemirror%2Faddon%2Fedit%2Fclosebrackets.js%2C%28import%29codemirror%2Faddon%2Fedit%2Fclosetag.js%2C%28import%29codemirror%2Faddon%2Fcomment%2Fcomment.js%2C%28import%29codemirror%2Faddon%2Ffold%2Ffoldcode.js%2C%28import%29codemirror%2Faddon%2Ffold%2Ffoldgutter.js%2C%28import%29codemirror%2Faddon%2Ffold%2Fbrace-fold.js%2C%28import%29codemirror%2Faddon%2Ffold%2Findent-fold.js%2C%28import%29codemirror%2Faddon%2Ffold%2Fcomment-fold.js&treeshake=%5BCodeMirror%5D%2C%5B*+as+CMjavascript%5D%2C%5B*+as+CMcss%5D%2C%5B*+as+CMhtmlmixed%5D%2C%5B*+as+CMclosebrackets%5D%2C%5B*+as+CMclosetag%5D%2C%5B*+as+CMcomment%5D%2C%5B*+as+CMfoldcode%5D%2C%5B*+as+CMfoldgutter%5D%2C%5B*+as+CMbraceFold%5D%2C%5B*+as+CMindentFold%5D%2C%5B*+as+CMcommentFold%5D&share=KYDwDg9gTgLgBAE2AMwIYFcA28DCEkCyAllFNAFCiSxwDe5ccOBAVqgG6oDOAxlEWBgAaBkwI8uXEY2YALGAFtMCoiGAJpYnpghdgAIyioeAa2Awpo5tt3nUAc03WIChcAB2wqwWQRMCHnxgJx8-BHt0GBhgKBDDY2AAMTCQonckT2T-EMDXDxgsjXIAXyA&config=%7B%22alias%22%3A%7B%22codemirror%22%3A%22codemirror%405%22%7D%7D) for the usage we have in the Repl.

**Comment by hugoattal** [comment]
You're right, I looked at the unpacked size 😅...

Still, I think that those packages were quite heavy only to write JSON, but I can still use it if you prefer (be it ace or codemirror)

> Anyway the code editor lib should be code-split with a dynamic import.

It will likely be loaded for a lot of stories with a somewhat complex props (with the auto-detect props)

So, what do you want me to do? I have no preference, it's really up to you 🙂 !

- Continue with this lite solution using shiki
- Use the ace editor
- Use the codemirror editor (didn't know this one, but might be a good choice!)

**Comment by Akryum** [comment]
> It will likely be loaded for a lot of stories with a somewhat complex props (with the auto-detect props)

A dynamic import will ensure it's only loaded when necessary, having it multiple times it not a problem.

> So, what do you want me to do?

I think codemirror would be a good choice.

**Comment by hugoattal** [comment]
Pfew, code mirror hasn't the best documentation, but I got it working 🥳!

Wdyt?
image

**Pull request merged**
